erver:
	# log only to syslog.
	log-only-syslog: yes

	ip-address: 185.230.141.184
	ip-address: 2a07:14c0:1:7503::10

	do-ip4: yes
	do-ip6: yes

        hide-version: yes
        hide-identity: no

        identity: "vlpn10.mooo.com DNS server"

remote-control:
	control-enable: yes
	control-interface: 127.0.0.1
	control-port: 8952
	server-key-file: "/etc/nsd/nsd_server.key"
	server-cert-file: "/etc//nsd/nsd_server.pem"
	control-key-file: "/etc/nsd/nsd_control.key"
	control-cert-file: "/etc/nsd/nsd_control.pem"

zone:
	name: "mooo.com"
	zonefile: "/etc/nsd/zones/mooo.com.zone"

include: "/etc/nsd/nsd.conf.d/*.conf"
