local		82.114.226.37
port		55550
proto		udp
dev		tun
topology	subnet
client-to-client
disable-dco

ca		/etc/openvpn/server/fvpn-ca.crt
cert		/etc/openvpn/server/cc00.crt
key		/etc/openvpn/server/cc00.key  # This file should be kept secret
dh		/etc/openvpn/server/dh.pem
tls-auth	/etc/openvpn/server/ta.key 0
duplicate-cn

cipher		AES-256-GCM
data-ciphers	AES-256-GCM

server			192.168.60.0 255.255.255.224
ifconfig-pool-persist	/etc/openvpn/server/ipp.txt

persist-tun
#allow-compression	yes
#comp-lzo		yes

keepalive	10 120
max-clients	20
user		openvpn
group		openvpn

client-config-dir	/etc/openvpn/ccd

status		/var/log/openvpn/status.log
log		/var/log/openvpn/openvpn.log
log-append	/var/log/openvpn/openvpn.log
verb		3
mute		5

explicit-exit-notify 1
