client
dev tun
proto udp
remote  82.114.226.37 55550
persist-key
persist-tun

ca		private/fbsd-ca.crt
cert		private/vlpn04-openvpn-client.crt
key		private/vlpn04-openvpn-client.key
tls-auth	private/ta.key 1

log		/var/log/ovpn.log
verb 3
mute 5

remote-cert-tls server
cipher		AES-256-GCM
data-ciphers	AES-256-GCM
