tos minclock 3 maxclock 6

pool 0.ru.pool.ntp.org iburst
pool ntp2.vniiftri.ru iburst
pool ntp.ix.ru iburst
pool ntp0.ru.net iburst

restrict default limited kod nomodify notrap noquery nopeer
restrict source  limited kod nomodify notrap noquery

restrict 127.0.0.1
restrict ::1

leapfile "/var/db/ntpd.leap-seconds.list"

logfile /var/log/ntp.log
