tcp_services = "{ 53, 80, 443, 62222 }"
udp_services = "{ 53, 123, 55550 }"

icmp_types = "{ echoreq, unreach }"

table <crowdsec-blacklists> persist
table <crowdsec6-blacklists> persist

set skip on lo0
#set skip on tun0

scrub in

block in all
pass out all keep state

block drop in quick from <crowdsec-blacklists> to any
block drop in quick from <crowdsec6-blacklists> to any

pass in proto tcp to port $tcp_services keep state
pass in proto udp to port $udp_services keep state

pass in inet proto icmp icmp-type $icmp_types keep state
