clear_tmp_enable="YES"
syslogd_flags="-ss"
sendmail_enable="NONE"
ntpd_sync_on_start="YES"
moused_nondefault_enable="NO"
dumpdev="NO"

sendmail_enable="NO"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"

daily_clean_hoststat_enable="NO"
daily_status_mail_rejects_enable="NO"
daily_status_include_submit_mailq="NO"
daily_submit_queuerun="NO"

hostname="ns01.fbsd.site"
ifconfig_vtnet0="inet 82.114.228.222 netmask 0xffffff00"
defaultrouter="82.114.228.1"

pf_enable="YES"
pf_rules="/etc/pf.conf"

crowdsec_enable="YES"
crowdsec_firewall_enable="YES"

qemu_guest_agent_enable="YES"
zabbix_agentd_enable="YES"
zabbix_server_enable="YES"

openvpn_enable="YES"
openvpn_flags="--tls-server"
openvpn_if="tun"
openvpn_configfile="/usr/local/etc/openvpn/server.conf"

node_exporter_enable="YES"
prometheus_enable="YES"
grafana_enable="YES"

sshd_enable="YES"
ntpd_enable="YES"
nsd_enable="YES"
mysql_enable="YES"

postfix_enable="YES"

php_fpm_enable="YES"
nginx_enable="YES"

nfs_server_enable="YES"
nfs_server_flags=" -u -t -n 3 -h 192.168.102.1"
rpcbind_enable="YES"
mountd_enable="YES"
