pkgs01: {
    url: "http://pkgs.crg.local:58080/default-default",
    mirror_type: "none",
    enabled: yes
}

pkgs02: {
    url: "http://pkgs.crg.local:58080/default-fbsd",
    mirror_type: "none",
    enabled: yes
}
